name: Deploy changes with release
on:
  release:
    types:
      - published

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy_backend:
    name: deploy backend to Fly.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy backend
        run: flyctl deploy
  deploy_frontend:
    name: deploy frontend to firebase hosting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: |
            cd frontend
            bun i
            bun run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entryPoint: ./frontend
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MATBACTIVITY }}
          channelId: live
          projectId: matbactivity
        env:
          NG_APP_AUTH0_DOMAIN: "${{ vars.REPOSITORY_VAR }}"
          NG_APP_AUTH0_CLIENT: "${{ vars.NG_APP_AUTH0_CLIENT }}"
          NG_APP_SERVER_DOMAIN: "${{ vars.NG_APP_SERVER_DOMAIN }}"
          NG_APP_SERVER_HTTP_PROTOCOL: "${{ vars.NG_APP_SERVER_HTTP_PROTOCOL }}"
          NG_APP_SERVER_WS_PROTOCOL: "${{ vars.NG_APP_SERVER_WS_PROTOCOL }}"
