name: Deploy changes with release
on:
  release:
    types:
      - published

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy_backend:
    name: Deploy backend to Fly.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy backend
        run: flyctl deploy